require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle'
    - 'bin/*'

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
